addSbtPlugin("org.scala-sbt.plugins" % "sbt-xjc" % "0.8")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "0.8.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-ghpages" % "0.5.4")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.3")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "1.0.1")
